version: '3'

services:
   app1:
     build: ./app1
     ports:
       - "8001:8000"

   app2:
     build: ./app2
     ports:
       - "8002:8000"

   app3:
     build: ./app3
     ports:
       - "8003:8000"

   nginx:
     build: ./
     ports:
       - "9000:80"
     depends_on:
       - app1
       - app2
       - app3
